### PR TITLE
Host for redirect as name for deployment

### PR DESCRIPTION
**Pull request by ntwcklng**
So it would be much easier to find a redirect that was created a while back ago

`$ now-redirect test.org`
```
> Deploying app that redirects all requests to http://test.org...
> Upload [====================] 100% 0.0s> Ready! https://httptestorg-nlbmsgtdyp.now.sh
 (copied to clipboard)
> Requests to https://httptestorg-nlbmsgtdyp.now.sh
/* will be redirected to http://test.org/*
> If it works as expected, alias it with:
  now alias https://httptestorg-nlbmsgtdyp.now.sh
 domain-to-be-redirected
```
`https://httptestorg-nlbmsgtdyp.now.sh` instead of `https://now-redirect-nlbmsgtdyp.now.sh`

### CODE REVIEW

**Comment by ntwcklng** [comment]
ping @vdanchenkov

**Comment by ntwcklng** [comment]
ping @vdanchenkov 🤓

**Comment by vdanchenkov** [comment]
HI, @ntwcklng, I don't like the idea of writing to file that resides inside the node_modules. There should be a way to do it without file system usage.

**Comment by ntwcklng** [comment]
hey @vdanchenkov, it will now use the bin argument `--name`  👍

**Review by vdanchenkov — APPROVED** [review]

**Pull request merged**
